version: '3.3'
services:
  kcapp_db:
    image: mysql:5.7
    command: mysqld --sql_mode=""
    restart: always
    environment:
      MYSQL_DATABASE: 'kcapp'
      MYSQL_USER: 'kcapp'
      MYSQL_PASSWORD: 'abcd1234'
      MYSQL_ROOT_PASSWORD: 'abcd1234'
    ports:
      - '3366:3306'
    expose:
      - '3366'
    volumes:
      - kcapp-db:/var/lib/mysql
volumes:
  kcapp-db:
